### ISSUE TITLE
Corrupt images warnings in Imagenet

### ISSUE THREAD

**Issue by barrh** [NervanaSystems/distiller#163] opened 2019-02-19 16:25 UTC
Often images from Imagenet dataset throw warnings during training.

There is an issue from python-pillow/pillow project that describes similar behavior: https://github.com/python-pillow/Pillow/issues/3337

The root cause is most probably found in the pillow library, but even if it's solved there, Distiller will still have to actively propagate the fix.

--------------
Example from distiller (with pretrained resnet50):

Epoch: [0][  300/ 2503]    Overall Loss 0.899065    Objective Loss 0.899065    Top1 77.972656    Top5 92.205078    LR 0.000500    Time 0.798467
/lib/python3.6/site-packages/PIL/TiffImagePlugin.py:763: UserWarning: Possibly corrupt EXIF data.  Expecting to read 2555904 bytes but only got 0. Skipping tag 0
  " Skipping tag %s" % (size, len(data), tag))
/lib/python3.6/site-packages/PIL/TiffImagePlugin.py:763: UserWarning: Possibly corrupt EXIF data.  Expecting to read 19660800 bytes but only got 0. Skipping tag 0
  " Skipping tag %s" % (size, len(data), tag))
/lib/python3.6/site-packages/PIL/TiffImagePlugin.py:763: UserWarning: Possibly corrupt EXIF data.  Expecting to read 18481152 bytes but only got 0. Skipping tag 0
  " Skipping tag %s" % (size, len(data), tag))
/lib/python3.6/site-packages/PIL/TiffImagePlugin.py:763: UserWarning: Possibly corrupt EXIF data.  Expecting to read 37093376 bytes but only got 0. Skipping tag 0
  " Skipping tag %s" % (size, len(data), tag))
/lib/python3.6/site-packages/PIL/TiffImagePlugin.py:763: UserWarning: Possibly corrupt EXIF data.  Expecting to read 39976960 bytes but only got 0. Skipping tag 0
  " Skipping tag %s" % (size, len(data), tag))
/lib/python3.6/site-packages/PIL/TiffImagePlugin.py:763: UserWarning: Possibly corrupt EXIF data.  Expecting to read 34865152 bytes but only got 0. Skipping tag 0
  " Skipping tag %s" % (size, len(data), tag))
/lib/python3.6/site-packages/PIL/TiffImagePlugin.py:780: UserWarning: Corrupt EXIF data.  Expecting to read 12 bytes but only got 10.
  warnings.warn(str(msg))
Epoch: [0][  400/ 2503]    Overall Loss 0.896776    Objective Loss 0.896776    Top1 78.037598    Top5 92.224121    LR 0.000500    Time 0.767407

**Comment by guyjacob** [comment] 2019-02-19 16:33
Yeah this one has been bugging me for a while. Great that you found the possible root cause.
It appears that the fix is fairly recent, so it's only available on the pillow master branch.
Did you check if it actually solves the problem? If so, we can think about how to integrate with it. Maybe fork from that specific commit or something...

**Comment by barrh** [comment] 2019-02-19 19:29
@guyjacob  I didn't test pillow's master branch. I agree it might be solved in (yet unreleased) master.
I don't think it's feasible to integrate a vertical fix, unless we release Distiller binaries. Don't forget pillow is _indirect_ dependency of Distiller, which is even more complicated. Before a fix is incorporated in pillow release (e.g. v6.0.0), there's not much we can do.

**Comment by barrh** [comment] 2019-04-02 20:04
Update: Pillow release 6.0.0 does seem to alleviate the issue.
With the new release, I get only a single warning per epoch, on my ImageNet dataset.

**Comment by levzlotnik** [comment] 2020-02-24 10:27
Hi,
Closing due to staleness.

**Closed by levzlotnik** 2020-02-24 10:27 UTC
