### ISSUE TITLE
prune conv filters will not process successor bn layers

### ISSUE THREAD

**Issue by Jie-Fang** [NervanaSystems/distiller#36] opened 2018-08-02 10:32 UTC
I meet a problem when i run the **pruning_filters_for_efficient_convnets** example which uses **resnet56_cifar_filter_rank.yaml**. One mistake i find is outdated document described this yaml. On the document website, it writes:

```
extensions:
  net_thinner:
      class: 'ResnetCifarFilterRemover'
      thinning_func_str: resnet_cifar_remove_filters
```
but in the yaml file, it use:
```
extensions:
  net_thinner:
      class: 'FilterRemover'
      thinning_func_str: remove_filters
      arch: 'resnet56_cifar'
      dataset: 'cifar10'
```

The net_thinner is different. There are no `ResnetCifarFilterRemover` class and `resnet_cifar_remove_filters` in the source code.

The biggest problem is the example cant work. I find when a conv layer remove some filters, it will not change the following bn layer. The error is below:

```
RuntimeError: running_mean should contain 7 elements not 16
```

I debug the code, it seems `create_thinning_recipe_filters` function in the thinning.py exists some bugs, it won't handle bn layers. [the line to handle bn layers](https://github.com/NervanaSystems/distiller/blob/master/distiller/thinning.py#L351)

**Comment by nzmora** [comment] 2018-08-02 14:33
Hi Jie-Fang,

Thanks for noticing the documentation error - I will fix that as soon as I can.  A few weeks ago I made changes in the "thinning" code so it is more generic, and I removed class ```ResnetCifarFilterRemover``` which was very specific (ResNet only), and I need to document this.

Regarding the failure you see: I pulled a clean copy of the code and built the example using the command-line from the YAML file and I can't recreate your issue:
```python3 compress_classifier.py -a=resnet56_cifar -p=50 ../../../data.cifar10 --epochs=70 --lr=0.1 --compress=../pruning_filters_for_efficient_convnets/resnet56_cifar_filter_rank.yaml --resume=checkpoint.resnet56_cifar_baseline.pth.tar -j=1 --deterministic```

I think that maybe you are using an old version of the code, that may have had a bug in it which is now fixed.  Please try and pull a clean version of the repository, and try it again.  If you still see an issue, please add the full log to the issue ticket and I'll dig into it.
Thanks!

**Comment by Jie-Fang** [comment] 2018-08-03 06:27
hi Neta,

Thank you for answering my question. 

I reclone the git repository, then rerun the script:
`python compress_classifier.py -a=resnet56_cifar -p=50 /home/jie/Documents/Datasets/cifar10 --epochs=70 --lr=0.1 --compress=../pruning_filters_for_efficient_convnets/resnet56_cifar_filter_rank.yaml --resume=/home/jie/Downloads/checkpoint.resnet56_cifar_baseline.pth.tar -j=1 --deterministic
`

But i still meet the issue. Here is my log(open DEBUG level):
[2018.08.03-141618.log](https://github.com/NervanaSystems/distiller/files/2256227/2018.08.03-141618.log)

My come dev envs listed below:
```
os: ubuntu 16.04
pytorch: 0.4
tensorflow: 1.9.0
python: 3.5
gcc: 5.4.0
```

**Comment by nzmora** [comment] 2018-08-05 00:57
Hi Jie-Fang,

I think the problem starts is in this line of code: https://github.com/NervanaSystems/distiller/blob/master/distiller/thinning.py#L323
Here is the first difference between your log:
```
2018-08-03 14:16:21,642 - ==> using cifar10 dataset
2018-08-03 14:16:21,642 - => creating resnet56_cifar model for CIFAR10
2018-08-03 14:16:21,717 - Invoking create_thinning_recipe_filters
2018-08-03 14:16:21,718 - SKipping module.conv1 shape=torch.Size([16, 3, 3, 3])
2018-08-03 14:16:21,718 - In tensor module.layer1.0.conv1.weight found 9/16 zero filters
2018-08-03 14:16:21,718 - SKipping module.layer1.0.conv2 shape=torch.Size([16, 16, 3, 3])
2018-08-03 14:16:21,720 - In tensor module.layer1.1.conv1.weight found 9/16 zero filters
2018-08-03 14:16:21,720 - SKipping module.layer1.1.conv2 shape=torch.Size([16, 16, 3, 3])
```
 
And my log:
```
2018-08-04 19:04:16,833 - ==> using cifar10 dataset
2018-08-04 19:04:16,833 - => creating resnet56_cifar model for CIFAR10
2018-08-04 19:04:17,222 - Invoking create_thinning_recipe_filters
2018-08-04 19:04:17,224 - SKipping module.conv1 shape=torch.Size([16, 3, 3, 3])
2018-08-04 19:04:17,224 - In tensor module.layer1.0.conv1.weight found 9/16 zero filters
2018-08-04 19:04:17,227 - [recipe] module.layer1.0.conv2: setting in_channels = 7
2018-08-04 19:04:17,228 - SKipping module.layer1.0.conv2 shape=torch.Size([16, 16, 3, 3])
2018-08-04 19:04:17,228 - In tensor module.layer1.1.conv1.weight found 9/16 zero filters
2018-08-04 19:04:17,230 - [recipe] module.layer1.1.conv2: setting in_channels = 7
2018-08-04 19:04:17,232 - SKipping module.layer1.1.conv2 shape=torch.Size([16, 16, 3, 3])
```
When pruning convolution filters (```out_channels```) of, for example, ```module.layer1.0.conv1.weight```, we need to change the number of channels (```in_channels```) of the next layers (e.g. ```module.layer1.0.conv2```).
This is what happens in these log lines:
```
2018-08-04 19:04:17,224 - In tensor module.layer1.0.conv1.weight found 9/16 zero filters
2018-08-04 19:04:17,227 - [recipe] module.layer1.0.conv2: setting in_channels = 7
```
And this takes place in the code lines: https://github.com/NervanaSystems/distiller/blob/master/distiller/thinning.py#L323:L334
From your log I infer that in your execution this line of code returns ```None```:
```
successors = sgraph.successors_f(normalize_module_name(layer_name), ['Conv', 'Gemm'])
```

So I wrote this short test: [test_issue36.py.txt](https://github.com/NervanaSystems/distiller/files/2259943/test_issue36.py.txt), which I ask you to try on your system (remove the .txt suffix from the filename - I have added it because github doesn't let us attach .py files).  Please make sure to edit the file and change the path to your copy of ```checkpoint.resnet56_cifar_baseline.pth.tar```.
Please run this test and report what happens.
A good run should look like this:
```
(env_pytorch_0.4) cvds_lab@cvds-18:~/nzmora/pytorch_workspace/distiller/tests$ pytest test_issue36.py
=========================================================================================================== test session starts ===========================================================================================================
platform linux -- Python 3.5.2, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /home/cvds_lab/nzmora/pytorch_workspace/distiller/tests, inifile:
collected 1 item

test_issue36.py .                                                                                                                                                                                                                   [100%]

======================================================================================================== 1 passed in 6.19 seconds =========================================================================================================
(env_pytorch_0.4) cvds_lab@cvds-18:~/nzmora/pytorch_workspace/distiller/tests$
```

**Comment by Jie-Fang** [comment] 2018-08-05 11:09
Hi Neta,

I run your test script, here is the result:
```
===================================================== test session starts =====================================================
platform linux -- Python 3.6.5, pytest-3.5.1, py-1.5.4, pluggy-0.6.0
rootdir: /home/jie/Documents/Codes/test/distiller/tests, inifile:
collected 1 item

test_issue36.py F                                                                                                       [100%]

========================================================== FAILURES ===========================================================
______________________________________________________ test_successorsh _______________________________________________________

    def test_successorsh():
        g = create_graph('cifar10', 'resnet56_cifar')
        assert g is not None

        op = g.find_op('layer1.0.conv1')
>       assert op is not None
E       assert None is not None

test_issue36.py:39: AssertionError
================================================== 1 failed in 3.17 seconds ===================================================
```

I debug the script and find that in the `graph` variable, `self.op` don't contain the `layer1.0.conv1`, it contains `module.layer1.0.conv1`,  all keys in the `self.op` have `module` prefix. Thus i change the layer name, like this:
```
def test_successorsh():
    g = create_graph('cifar10', 'resnet56_cifar')
    assert g is not None

    op = g.find_op('module.layer1.0.conv1')
    assert op is not None

    succs = g.successors_f('module.layer1.0.conv1', 'Conv', [], logging)
    assert ['module.layer1.0.conv2'] == succs
```

The test result is successful. 

```
===================================================== test session starts =====================================================
platform linux -- Python 3.6.5, pytest-3.5.1, py-1.5.4, pluggy-0.6.0
rootdir: /home/jie/Documents/Codes/test/distiller/tests, inifile:
collected 1 item

test_issue36.py .                                                                                                       [100%]

================================================== 1 passed in 3.09 seconds ===================================================
```

**Comment by Jie-Fang** [comment] 2018-08-06 03:42
Hi Neta,

According to my test results, i read your code. 

If a model is created by setting `parallel = True` in  the code: https://github.com/NervanaSystems/distiller/blob/master/models/__init__.py#L41, the model's parameter will contain `module.` prefix.

`checkpoint.resnet56_cifar_baseline.pth.tar` is wrapped with a DataParallel Module, in the code: https://github.com/NervanaSystems/distiller/blob/master/distiller/utils.py#L59, you remove the `module.` prefix. But when creating graph, it uses `parallel` to create a model, like this: https://github.com/NervanaSystems/distiller/blob/master/distiller/thinning.py#L73, which makes the model contain the `module.` prefix. 

Thus I set the `parallel` parameter False when creating graph, then run the `pruning_filters_for_efficient_convnets` example which uses `resnet56_cifar_filter_rank.yaml`, it successes.

I'm not sure whether it's appropriate to set the `parallel` False and confused that why you can run it without setting the `parallel` False.

**Comment by ndronen** [comment] 2018-08-20 16:56
I've encountered the same problem ([gist of output](https://gist.github.com/ndronen/5beb2dce647fa1581b0c8dd3b4bcb48f)). @nzmora, while you're trying to determine the cause of the problem, can you provide a known commit of `distiller` that has a working example of "Pruning Filters for Efficient Convnets"? It would allow @Jie-Fang, me, and others to evaluate the package's capabilities in the meantime.

**Comment by nzmora** [comment] 2018-08-20 21:43
Hi @ndronen and @Jie-Fang 

I'm sorry if this issue held up your work.
A couple of clarifications:
1. As @Jie-Fang pointed out above, the test I sent was incorrect.
2. On my system I do not experience the problem you report; even when I force PyTorch to use one GPU (this is the difference between Jie's setup: 1 GPU, and mine: 4 GPUs).

@Jie-Fang hit the problem on the head when he explained above that https://github.com/NervanaSystems/distiller/blob/master/distiller/thinning.py#L73 should use parallel=False.

I created branch issue_36 (https://github.com/NervanaSystems/distiller/tree/issue_36) with Jie's fix and some logs.  The logs might help me understand why I don't see the issue on my end.  
Please test this fix, and send me the outputs when ```parallel=True``` and when ```parallel=False``` in https://github.com/NervanaSystems/distiller/blob/master/distiller/thinning.py#L73.

Thanks for your help!
Neta

**Comment by Jie-Fang** [comment] 2018-08-30 12:53
Hi @nzmora 

Thank you for your help. By the way, It doesn't hold my work. 

I tested issue_36, these two logs were obtained by setting `parallel=True or False` respectively.
[set_false.log](https://github.com/NervanaSystems/distiller/files/2336173/set_false.log)
[set_true.log](https://github.com/NervanaSystems/distiller/files/2336174/set_true.log)

In addition, I've got some useful info that may help you:
In a machine with 4 GPUs, the code runs successfully without any changes. If I set `--gpus=0`, it also works. But in a machine with only one GPU, it only works when I set `parallel=False`.

**Comment by nzmora** [comment] 2018-08-30 22:40
Thanks @Jie-Fang ,

I'm away from the office next week, so I'm glad you have a temporary bypass for this issue until I get it resolved.
Thanks for the logs and the info about the 1/4 GPUs.
Cheers,
Neta

**Closed** 2019-08-23 14:07 UTC
