### ISSUE TITLE
Is it applicable to regression models?

### ISSUE THREAD

**Issue by Yvette1993** [NervanaSystems/distiller#232] opened 2019-04-22 09:16 UTC
Can I use compress_classifier.py for regression model? Where need to changed if I want do it?

**Comment by nzmora** [comment] 2019-04-28 10:33
Hi @Yvette1993,

You should be able to use Distiller for regression models.  
```compress_classifier.py``` is an example application for image classification.  
The distinction between the two is that Distiller is a library, and ```compress_classifier.py``` is an application that uses Distiller for compression.  We have a [simpler sample application](https://github.com/NervanaSystems/distiller/blob/master/examples/word_language_model/main.py), for compressing language-models, that might be easier to follow (see detailed tutorial [here](https://nervanasystems.github.io/distiller/tutorial-lang_model.html)).

There's some explanation [here](https://nervanasystems.github.io/distiller/design.html) on the basic flow, and Figure 1 [here](https://nervanasystems.github.io/distiller/schedule.html#pruning-fine-control) provides explains in more detail the Distiller callbacks that you need to invoke from your application.

I hope these suffice.  If not, let me know (unfortunately we don't have an explicit tutorial targeting how to add Distiller to your applications).
Cheers
Neta

**Comment by levzlotnik** [comment] 2020-02-19 13:59
Hi,

Closing this issue since it seems resolved. Feel free to reopen if there are any further questions.

**Closed by levzlotnik** 2020-02-19 13:59 UTC
Labels: question
