### ISSUE TITLE
[AMC] can't refine the model

### ISSUE THREAD

**Issue by HKLee2040** [NervanaSystems/distiller#130] opened 2019-01-22 02:56 UTC
Clone the amc repository @ 1/16
Single GPU is used, "mac-constrained" protocol
The command is shown below:
python3 compress_classifier.py --arch=plain20_cifar ../../../data.cifar10 --amc --resume=../cifar10/checkpoint.plain20_cifar.pth.tar --lr=0.05 --amc-action-range 0.0 0.80 --vs=0.1 --amc-target-density 0.5
The best accuracy can achieve 83.4%

However, I can't finetune the model, and show me the following error message:

$ python3 compress_classifier.py --arch=plain20_cifar ../../../data.cifar10 --resume=logs/2019.01.21-132420/BEST_adc_episode_1021_checkpoint.pth.tar --compress=../automated_deep_compression/plain20_cifar_baseline_training.yaml --epochs=180 --batch=128 --lr=0.1
Log file for this run: /media/walker/Data/work/distiller_amc2/examples/classifier_compression/logs/2019.01.22-103808/2019.01.22-103808.log
==> using cifar10 dataset
=> creating plain20_cifar model for CIFAR10

--------------------------------------------------------
Logging to TensorBoard - remember to execute the server:
> tensorboard --logdir='./logs'

=> loading checkpoint logs/2019.01.21-132420/BEST_adc_episode_1021_checkpoint.pth.tar
Checkpoint keys:
thinning_recipes
	compression_sched
	arch
	state_dict
	epoch

Log file for this run: /media/walker/Data/work/distiller_amc2/examples/classifier_compression/logs/2019.01.22-103808/2019.01.22-103808.log
Traceback (most recent call last):
  File "compress_classifier.py", line 854, in <module>
    main()
  File "compress_classifier.py", line 356, in main
    model, chkpt_file=args.resume)
  File "/media/walker/Data/work/distiller_amc2/apputils/checkpoint.py", line 97, in load_checkpoint
    compression_scheduler.load_state_dict(checkpoint['compression_sched'])
  File "/media/walker/Data/work/distiller_amc2/distiller/scheduler.py", line 212, in load_state_dict
    masker.mask = loaded_masks[name]
KeyError: 'module.layer3.1.conv2.weight'

Does the model format be changed?

**Comment by HKLee2040** [comment] 2019-01-24 02:54
Hi @nzmora 

Yes, it works after I update the code.  Thanks.

**Comment by HKLee2040** [comment] 2019-01-27 02:09
Although the AMC result can achieve 83.4% top-1 accuracy, but the result of finetuned model is still 88.x% top-1 accuracy.
However, if I apply the 8-bit quantization on finetuned model, the accuracy can achieve 90.x%.

**Comment by nzmora** [comment] 2019-01-27 09:08
Hi @HKLee2040,

This is very interesting.  Did you compress Plain20 with AMC+PPO and then quantized to 8-bit?
Can you share the command-line?

Below I am quantizing a Plain20 model that I compressed (50% MACs) using AMC+PPO, to produce a Top1=89%.  The quantized version produces a Top1=88.56: 
```
--- test ---------------------
10000 samples (256 per mini-batch)
Test: [   10/   40]    Loss 0.432296    Top1 88.359375    Top5 99.492188
Test: [   20/   40]    Loss 0.419661    Top1 88.203125    Top5 99.550781
Test: [   30/   40]    Loss 0.408907    Top1 88.554688    Top5 99.557292
Test: [   40/   40]    Loss 0.397659    Top1 88.560000    Top5 99.530000
==> Top1: 88.560    Top5: 99.530    Loss: 0.398
```
Thanks!
Neta

**Comment by HKLee2040** [comment] 2019-01-27 15:00
@nzmora 
It's AMC+ClippedPPO --> refine, and then quantized to 8-bit.

However, if finetune with following schedule /wo quantization, it can achieve 90.x%, too.

lr_schedulers:
  training_lr:
    class: StepLR
    step_size: 10
    gamma: 0.3

policies:
    - lr_scheduler:
        instance_name: training_lr
      starting_epoch: 1579
      ending_epoch: 1659
      frequency: 1

command-line:

python3 compress_classifier.py --arch=plain20_cifar ../../../data.cifar10 --amc --resume=../cifar10/checkpoint.plain20_cifar.pth.tar --lr=0.05 --amc-action-range 0.0 0.80 --vs=0.1 --amc-target-density=0.5

python compress_classifier.py -a plain20_cifar -p 50 -b 128 ../../../data.cifar10 --epochs 80 --compress=../quantization/quant_aware_train_linear_quant_plain20_t.yaml -j 1 --lr 0.1 --vs 0 --wd=0.0002 --resume=logs/2019.01.24-215533/BEST_adc_episode_1579_checkpoint.pth.tar

--- test ---------------------
10000 samples (128 per mini-batch)
Test: [   50/   79]    Loss 0.344426    Top1 90.187500    Top5 99.671875    
Test: [   79/   79]    Loss 0.348614    Top1 90.070000    Top5 99.660000    
==> Top1: 90.070    Top5: 99.660    Loss: 0.349

**Comment by HKLee2040** [comment] 2019-01-27 15:04
In this case "It's AMC+ClippedPPO --> refine, and then quantized to 8-bit."

2019-01-27 07:30:24,871 - App args: ['compress_classifier.py', '-a', 'plain20_cifar', '-p', '50', '-b', '128', '../../../data.cifar10', '--epochs', '300', '--compress=../quantization/preact_plain20_cifar_pact.yaml', '-j', '1', '--lr', '0.1', '--vs', '0', '--wd=0.0002', '--resume=../cifar10/plain20/best.pth.tar']

The preact_plain20_cifar_pact.yaml is

quantizers:
  pact_quantizer:
    class: PACTQuantizer
    act_clip_init_val: 8.0
    bits_activations: 8
    bits_weights: 8

lr_schedulers:
  training_lr:
    class: StepLR
    step_size: 25
    gamma: 0.3

policies:
    - quantizer:
        instance_name: pact_quantizer
      starting_epoch: 1630
      ending_epoch: 1930
      frequency: 1

    - lr_scheduler:
        instance_name: training_lr
      starting_epoch: 1630
      ending_epoch: 1930
      frequency: 1

2019-01-27 16:35:04,742 - --- test ---------------------
2019-01-27 16:35:04,742 - 10000 samples (128 per mini-batch)
2019-01-27 16:35:06,285 - Test: [   50/   78]    Loss 0.405032    Top1 89.875000    Top5 99.625000    
2019-01-27 16:35:07,155 - ==> Top1: 90.020    Top5: 99.660    Loss: 0.404


I guess lr_scheduler play some role in the finetune.

**Comment by nzmora** [comment] 2019-01-27 15:32
Very cool - I'll try reproducing later today.
Thanks!
Neta

**Comment by HKLee2040** [comment] 2019-04-05 08:57
@nzmora 
I try this case but got some error message:

amc command:
compress_classifier.py --arch=vgg16_cifar ../../../data.cifar10 --resume=../cifar10/checkpoint.vgg16_cifar.pth.tar --lr=0.05 --amc --amc-protocol=mac-constrained --amc-target-density=0.2 -p=50 --amc-agent-algo ClippedPPO-discrete

model refine command:
compress_classifier.py -a vgg16_cifar -p 50 -b 128 ../../../data.cifar10 --epochs 80 --compress=../quantization/preact_plain20_cifar_pact.yaml -j 1 --lr 0.1 --vs 0 --wd=0.0002 --resume=logs/2019.04.02-225558/BEST_adc_episode_1507_checkpoint.pth.tar

error message:
2019-04-05 16:50:33,381 - Traceback (most recent call last):
  File "compress_classifier.py", line 749, in <module>
    main()
  File "compress_classifier.py", line 260, in main
    msglogger.info(distiller.masks_sparsity_tbl_summary(model, compression_scheduler))
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/media/walker/Data/work/distiller_0320/distiller/data_loggers/collector.py", line 465, in collectors_context
    yield collectors_dict
  File "compress_classifier.py", line 255, in main
    loggers=[tflogger, pylogger], args=args)
  File "compress_classifier.py", line 361, in train
    loss.backward()
  File "/media/walker/Data/work/env/lib/python3.5/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/media/walker/Data/work/env/lib/python3.5/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

preact_plain20_cifar_pact.yaml is:
quantizers:
  pact_quantizer:
    class: PACTQuantizer
    act_clip_init_val: 8.0
    bits_activations: 8
    bits_weights: 8

lr_schedulers:
  training_lr:
    class: StepLR
    step_size: 25
    gammas: 0.3

policies:
    - quantizer:
        instance_name: pact_quantizer
      starting_epoch: 1507
      ending_epoch: 1930
      frequency: 1

    - lr_scheduler:
        instance_name: training_lr
      starting_epoch: 1507
      ending_epoch: 1930
      frequency: 1

**Comment by HKLee2040** [comment] 2019-04-05 09:07
Other information is shown below
2019-04-05 16:50:28,671 - Log file for this run: /media/walker/Data/work/distiller_0320/examples/classifier_compression/logs/2019.04.05-165028/2019.04.05-165028.log
2019-04-05 16:50:28,672 - Number of CPUs: 8
2019-04-05 16:50:28,690 - Number of GPUs: 1
2019-04-05 16:50:28,690 - CUDA version: 9.0.176
2019-04-05 16:50:28,691 - CUDNN version: 7402
2019-04-05 16:50:28,691 - Kernel: 4.15.0-47-generic
2019-04-05 16:50:28,691 - Python: 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]
2019-04-05 16:50:28,692 - PyTorch: 1.0.1
2019-04-05 16:50:28,692 - Numpy: 1.16.0
2019-04-05 16:50:28,826 - Git is dirty
2019-04-05 16:50:28,826 - Active Git branch: master
2019-04-05 16:50:28,839 - Git commit: 90226b1cd38d2210e6fb7da988e28ce721b65804

**Comment by nzmora** [comment] 2019-08-06 21:44
Hi @HKLee2040 ,

I'm closing because this refers to the older implementation of AMC.  I hope the revised version will be more beneficial.
Feel free to reopen if you see a need.
Cheers
Neta

**Closed by nzmora** 2019-08-06 21:44 UTC
Labels: automated compression
