### ISSUE TITLE
ModuleNotFoundError: No module named 'distiller'

### ISSUE THREAD

**Issue by nathanhubens** [NervanaSystems/distiller#332] opened 2019-07-23 14:18 UTC
After following the installation guide, I wanted to try the `compress_classifier.py` example. But it tells me that it is unable to find the distiller module. The same error occurs when I try running the notebooks.

I have CUDA 9.2 and PyTorch 1.1 and I had no error during the installation stage. What should I do ?

**Comment by guyjacob** [comment] 2019-07-23 14:57
It's hard to say without more info.
* Which OS are you running on?
* Are you sure you created a virtualenv, activated it and then ran the `pip install -e .` command from the Distiller directory? Any errors popped up during the installation?
* When running the script, you're in the activated virtualenv?

(Apologies if these questions seem redundant - just trying to make sure I understand the steps you took)

Can you try running `pip list | grep distiller` and see what you get? If the package was installed properly, it should be listed. And if it's listed then I can't think of a reason it won't be found when importing.

If none of the above helps to root cause the problem, please provide more details on what the steps you took and we'll try to help.

**Comment by nathanhubens** [comment] 2019-07-24 08:40
I use Ubuntu 18.04.

Here are the steps I followed during the installation:

1.  activate the virtual environment (I use Conda)
2. `git clone https://github.com/NervanaSystems/distiller.git`
3. `cd distiller`
4. `pip3 install -e .` -> No error occured
5. run the script `python3 compress_classifier.py --help` -> This leads to the error `python3 compress_classifier.py --help`

When I try to run the following command `pip list | grep distiller` I get nothing. But if I use pip3, I have `distiller (0.4.0rc0, /home/nathan/distiller)`. It seems that the library has been installed outside of the scope of my virtual environment.

**Comment by levzlotnik** [comment] 2019-07-24 15:02
Yes that happens sometimes with `virtualenv`, sometimes it creates `python3` and `pip3` in the new dir, but `pip` and `python` remain the old aliases. Try running `which pip`, and you'll probably see `/usr/bin/pip` or something like that...

**Comment by nzmora** [comment] 2019-07-27 15:39
Hi @nathanhubens ,

We don't usually use Conda, so the mixing of Conda and pip can be to blame - although I don't think so.
To create the virtual environment, did you use ```$ python3 -m virtualenv env```  or ```python3 -m venv env```?  I wonder if the latter is giving you a problem?

Thanks!
Neta

**Comment by nathanhubens** [comment] 2019-08-09 15:17
Hi @nzmora, 

I used a conda virtual environment, created with `conda create -n env`, so it is neither of them. Everything now works fine using `virtualenv` 

Thank you !

**Comment by nzmora** [comment] 2019-08-11 22:38
Glad to hear!  I'm closing the issue.
Cheers
Neta

**Closed by nzmora** 2019-08-11 22:38 UTC
