### ISSUE TITLE
can not work for object detection model

### ISSUE THREAD

**Issue by Jakel21** [NervanaSystems/distiller#247] opened 2019-05-09 02:21 UTC
I tried to use distiller for my cascade rcnn model but it did not work for me and i need some help.

I used AGP pruning method and followed the schedule introduced in the guide doc to change my training code, and the backbone resnet50(used in senet model) parameters were selected to prune. However in the process the total sparsity just was 0. It failed. What is the problem and how should i adjust?? 

in epoch loop:
<img width="541" alt=" e" src="https://user-images.githubusercontent.com/20606275/57422719-bb2a5600-7243-11e9-9ca3-2421bf6992f6.png">
in train function：
<img width="725" alt="t" src="https://user-images.githubusercontent.com/20606275/57422723-bfef0a00-7243-11e9-9f43-85fbb76ba7ee.png">
when i want to see the mask info, i get this error:
<img width="615" alt="err" src="https://user-images.githubusercontent.com/20606275/57422731-c67d8180-7243-11e9-8938-7ed3a27291c5.png">
 i don't know why the mask is not working and i think the masks are set when epoch begin.
ps: i just can't see any model compression project support object detection, including distiller and pocketflow? Why? What is the difference between object detection problems  and classification model when we try to compress them ?? 

looking forward to you answer~3q

**Comment by nzmora** [comment] 2019-05-09 19:20
Hi @Jakel21,

From the error you get on line 400, it is evident that ```self.compression_scheduler" is None.  This is the ```AttributeError``` that you receive.
Did you instantiate the scheduler and give it the pruning schedule? -- I don't see it in the code that you pasted.
Cheers,
Neta

**Comment by Jakel21** [comment] 2019-05-10 02:57
> Hi @Jakel21,
> 
> From the error you get on line 400, it is evident that `self.compression_scheduler" is None. This is the `AttributeError``` that you receive.
> Did you instantiate the scheduler and give it the pruning schedule? -- I don't see it in the code that you pasted.
> 
> Regarding your question about support for pruning object-detectors: traditionally most of the research (but not all) about model compression has (and is) performed on image classifiers. It's mostly a matter of convenience I think. There's no particular reason Distiller doesn't support compression of object detectors except for priorities. As far as I know, some people using Distiller have used it to compress object-detection models, but I can't be sure. We'd love it if someone from the community contributed an example.
> 
> Cheers,
> Neta

Thanks for the reply~
my compress scheduler looks like this:
----------------------------------------------------------------------------------------
version: 1

pruners:
  fc_pruner:
    class: AutomatedGradualPruner
    initial_sparsity: 0.0
    final_sparsity: 0.75
    weights: [
    module.backbone.model.layer1.0.se_module.fc1.weight,
    module.backbone.model.layer1.0.se_module.fc2.weight,
    module.backbone.model.layer1.1.se_module.fc1.weight,
    module.backbone.model.layer1.1.se_module.fc2.weight,
    module.backbone.model.layer1.2.se_module.fc1.weight,
    module.backbone.model.layer1.2.se_module.fc2.weight,
    module.backbone.model.layer2.0.se_module.fc1.weight,
    module.backbone.model.layer2.0.se_module.fc2.weight,
    module.backbone.model.layer2.1.se_module.fc1.weight,
    module.backbone.model.layer2.1.se_module.fc2.weight,
    module.backbone.model.layer2.2.se_module.fc1.weight,
    module.backbone.model.layer2.2.se_module.fc2.weight,
    module.backbone.model.layer2.3.se_module.fc1.weight,
    module.backbone.model.layer2.3.se_module.fc2.weight,
    module.backbone.model.layer3.0.se_module.fc1.weight,
    module.backbone.model.layer3.0.se_module.fc2.weight,
    module.backbone.model.layer3.1.se_module.fc1.weight,
    module.backbone.model.layer3.1.se_module.fc2.weight,
    module.backbone.model.layer3.2.se_module.fc1.weight,
    module.backbone.model.layer3.2.se_module.fc2.weight,
    module.backbone.model.layer3.3.se_module.fc1.weight,
    module.backbone.model.layer3.3.se_moduel.fc2.weight,
    module.backbone.model.layer3.4.se_module.fc1.weight,
    module.backbone.model.layer3.4.se_module.fc2.weight,
    module.backbone.model.layer3.5.se_module.fc1.weight,
    module.backbone.model.layer3.5.se_module.fc2.weight,
    module.backbone.model.layer4.0.se_module.fc1.weight,
    module.backbone.model.layer4.0.se_module.fc2.weight,
    module.backbone.model.layer4.1.se_module.fc1.weight,
    module.backbone.model.layer4.1.se_module.fc2,weight,
    module.backbone.model.layer4.2.se_module.fc1.weight,
    module.backbone.model.layer4.2.se_module.fc2.weight]

  conv_pruner:
    class: AutomatedGradualPruner
    initial_sparsity: 0.0
    final_sparsity: 0.75
    weights: [
    module.backbone.model.layer0.conv1.weight,
    module.backbone.model.layer1.0.conv1.weight,
    module.backbone.model.layer1.0.conv2.weight,
    module.backbone.model.layer1.0.conv3.weight,
    module.backbone.model.layer1.0.downsample.0.weight,
    module.backbone.model.layer1.1.conv1.weight,
    module.backbone.model.layer1.1.conv2.weight,
    module.backbone.model.layer1.1.conv3.weight,
    module.backbone.model.layer1.2.conv1.weight,
    module.backbone.model.layer1.2.conv2.weight,
    module.backbone.model.layer1.2.conv3.weight,
    module.backbone.model.layer2.0.conv1.weight,
    module.backbone.model.layer2.0.conv2.weight,
    module.backbone.model.layer2.0.conv3.weight,
    module.backbone.model.layer2.0.downsample.0.weight,
    module.backbone.model.layer2.1.conv1.weight,
    module.backbone.model.layer2.1.conv2.weight,
    module.backbone.model.layer2.1.conv3.weight,
    module.backbone.model.layer2.2.conv1.weight,
    module.backbone.model.layer2.2.conv2.weight,
    module.backbone.model.layer2.2.conv3.weight,
    module.backbone.model.layer2.3.conv1.weight,
    module.backbone.model.layer2.3.conv2.weight,
    module.backbone.model.layer2.3.conv3.weight,
    module.backbone.model.layer3.0.conv1.weight,
    module.backbone.model.layer3.0.conv2.weight,
    module.backbone.model.layer3.0.downsample.0.weight,
    module.backbone.model.layer3.1.conv1.weight,
    module.backbone.model.layer3.1.conv2.weight,
    module.backbone.model.layer3.1.conv3.weight,
    module.backbone.model.layer3.2.conv1.weight,
    module.backbone.model.layer3.2.conv2.weight,
    module.backbone.model.layer3.2.conv3.weight,
    module.backbone.model.layer3.3.conv1.weight,
    module.backbone.model.layer3.3.conv2.weight,
    module.backbone.model.layer3.3.conv3.weight,
    module.backbone.model.layer3.4.conv1.weight,
    module.backbone.model.layer3.4.conv2.weight,
    module.backbone.model.layer3.4.conv3.weight,
    module.backbone.model.layer3.5.conv1.weight,
    module.backbone.model.layer3.5.conv2.weight,
    module.backbone.model.layer3.5.conv3.weight,
    module.backbone.model.layer4.0.conv1.weight,
    module.backbone.model.layer4.0.conv2.weight,
    module.backbone.model.layer4.0.conv3.weight,
    module.backbone.model.layer4.0.downsample.0.weight,
    module.backbone.model.layer4.1.conv1.weight,
    module.backbone.model.layer4.1.conv2.weight,
    module.backbone.model.layer4.1.conv3.weight,
    module.backbone.model.layer4.2.conv1.weight,
    module.backbone.model.layer4.2.conv2.weight,
    module.backbone.model.layer4.2.conv3.weight]

policies:
  - pruner:
      instance_name: conv_pruner
    starting_epoch: 0
    ending_epoch: 50
    frequency: 1

  - pruner:
      instance_name: fc_pruner
    starting_epoch: 0
    ending_epoch: 50
    frequency: 1
----------------------------------------------------------------------------------------

and i  config the scheduler at the first part of my code:
<img width="631" alt="sc" src="https://user-images.githubusercontent.com/20606275/57499128-0f4f3c00-7311-11e9-9014-e2727180b857.png">
is there any problem in my config scheduler file or my process of the config? i just follow the introduction guide of the word language model in examples.

**Comment by nzmora** [comment] 2019-05-10 07:57
Hi @Jakel21,

The schedule and the instantiation of ```self.compression_scheduler``` look good.  However, from the error you sent:

https://user-images.githubusercontent.com/20606275/57422731-c67d8180-7243-11e9-8938-7ed3a27291c5.png

It is evident that ```self.compression_scheduler``` is None.  If this is not clear to you, here is the simplest way to reproduce the error message:
```
>>> a = None
>>> a.zeros_mask_dict
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'zeros_mask_dict'
```
I haven't used ```mmdetection``` and I don't know how you integrated Distiller, so without seeing the entire code, I don't think I can help further.
Cheers,
Neta

**Comment by Jakel21** [comment] 2019-05-10 08:01
> Hi @Jakel21,
> 
> The schedule and the instantiation of `self.compression_scheduler` look good. However, from the error you sent:
> 
> https://user-images.githubusercontent.com/20606275/57422731-c67d8180-7243-11e9-8938-7ed3a27291c5.png
> 
> It is evident that `self.compression_scheduler` is None. If this is not clear to you, here is the simplest way to reproduce the error message:
> 
> ```
> >>> a = None
> >>> a.zeros_mask_dict
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: 'NoneType' object has no attribute 'zeros_mask_dict'
> ```
> 
> I haven't used `mmdetection` and I don't know how you integrated Distiller, so without seeing the entire code, I don't think I can help further.
> Cheers,
> Neta

i will work on it and try to make it work. Thanks for the help anyway.

**Comment by saranshkarira** [comment] 2019-06-19 07:05
try this:
`if compression_scheduler is None:                                                                                                                                                                                                
        compression_scheduler = distiller.CompressionScheduler(model)`

**Comment by nzmora** [comment] 2019-06-19 10:55
BTW, @levzlotnik is adding an example for pruning object detectors.  This will be shared on github in a couple of weeks I hope.
Cheers,
Neta

**Comment by saranshkarira** [comment] 2019-06-20 10:40
I'm working on them as well, lemme know if need any assistance! @levzlotnik

**Comment by RizhaoCai** [comment] 2019-07-31 12:32
> > Hi @Jakel21,
> > The schedule and the instantiation of `self.compression_scheduler` look good. However, from the error you sent:
> > https://user-images.githubusercontent.com/20606275/57422731-c67d8180-7243-11e9-8938-7ed3a27291c5.png
> > It is evident that `self.compression_scheduler` is None. If this is not clear to you, here is the simplest way to reproduce the error message:
> > ```
> > >>> a = None
> > >>> a.zeros_mask_dict
> > Traceback (most recent call last):
> >   File "<stdin>", line 1, in <module>
> > AttributeError: 'NoneType' object has no attribute 'zeros_mask_dict'
> > ```
> > 
> > 
> > I haven't used `mmdetection` and I don't know how you integrated Distiller, so without seeing the entire code, I don't think I can help further.
> > Cheers,
> > Neta
> 
> i will work on it and try to make it work. Thanks for the help anyway.

Hey dude. Have you solved this problem?

**Comment by levzlotnik** [comment] 2019-07-31 12:35
Hey guys, I am working on the torchvision object detection sample at the moment, hopefully will push it soon.

**Comment by RizhaoCai** [comment] 2019-11-29 02:31
> Hey guys, I am working on the torchvision object detection sample at the moment, hopefully will push it soon.

Hello, how is it now?

**Comment by bupt-renpei** [comment] 2020-01-26 22:51
@RizhaoCai Hello, Rizhao, can you pls share your development expreience?

**Comment by bupt-renpei** [comment] 2020-01-26 22:52
@levzlotnik Hi dude, have you finish the object detection compression samples? Thanks for your efforts!

**Comment by RizhaoCai** [comment] 2020-01-29 07:01
> @RizhaoCai Hello, Rizhao, can you pls share your development expreience?

The object detection example has been updated
https://github.com/NervanaSystems/distiller/tree/master/examples/object_detection_compression

**Comment by bupt-renpei** [comment] 2020-01-29 14:14
Hi Rizhao,


Thanks for your help. But I cannot see any change in&nbsp;examples/object_detection_compression, can you give some hints?


Thanks again.


Best,


Pei

&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by RizhaoCai** [comment] 2020-01-31 07:29
> @RizhaoCai Hi Rizhao, Thanks for your help. But I cannot see any change in&nbsp;examples/object_detection_compression, can you give some hints?

What do you can't see any change? 
Can you open the link "https://github.com/NervanaSystems/distiller/tree/master/examples/object_detection_compression"?

My experience is quite straightforward. 
I just ran the example 'compress_detector.py' given by the link.
And I wrote my version compress_detector.py and put my model (RFB-Net), train_fn, evaluate_fn, data_loader to the code. That is it.

**Comment by levzlotnik** [comment] 2020-02-19 12:43
Hi, 
Closing this issue since the object detection example has been added several months ago, so please refer to it.

**Closed by levzlotnik** 2020-02-19 12:43 UTC
Labels: object detection, pruning, question
